module.exports = [  
   {  
      'long':'',
      'short':''
   },
   {  
      'long':'YOU ARE STANDING AT THE END OF A ROAD BEFORE A SMALL BRICK BUILDING . AROUND YOU IS A FOREST. A SMALL STREAM FLOWS OUT OF THE BUILDING AND DOWN A GULLY.',
      'short':'YOU\'RE AT END OF ROAD AGAIN.'
   },
   {  
      'long':'YOU HAVE WALKED UP A HILL, STILL IN THE FOREST. THE ROAD NOW SLOPES BACK DOWN THE OTHER SIDE OF THE HILL. THERE IS A BUILDING IN THE DISTANCE.',
      'short':'YOU\'RE AT HILL IN ROAD.'
   },
   {  
      'long':'YOU ARE INSIDE A BUILDING, A WELL HOUSE FOR A LARGE SPRING.',
      'short':'YOU\'RE INSIDE BUILDING.'
   },
   {  
      'long':'YOU ARE IN A VALLEY IN THE FOREST BESIDE A STREAM TUMBLING ALONG A ROCKY BED.',
      'short':'YOU\'RE IN VALLEY.'
   },
   {  
      'long':'YOU ARE IN OPEN FOREST, WITH A DEEP VALLEY TO ONE SIDE.',
      'short':'YOU\'RE IN FOREST.'
   },
   {  
      'long':'YOU ARE IN OPEN FOREST NEAR BOTH A VALLEY AND A ROAD.',
      'short':'YOU\'RE IN FOREST.'
   },
   {  
      'long':'AT YOUR FEET ALL THE WATER OF THE STREAM SPLASHES INTO A 2 INCH SLIT IN THE ROCK. DOWNSTREAM THE STREAMBED IS BARE ROCK.',
      'short':'YOU\'RE AT SLIT IN STREAMBED.'
   },
   {  
      'long':'YOU ARE IN A 20 FOOT DEPRESSION FLOORED WITH BARE DIRT. SET INTO THE DIRT IS A STRONG STEEL GRATE MOUNTED IN CONCRETE. A DRY STREAMBED LEADS INTO THE DEPRESSION.',
      'short':'YOU\'RE OUTSIDE GRATE'
   },
   {  
      'long':'YOU ARE IN A SMALL CHAMBER BENEATH A 3X3 STEEL GRATE TO THE SURFACE. A LOW CRAWL OVER COBBLES LEADS INWARD TO THE WEST.',
      'short':'YOU\'RE BELOW THE GRATE'
   },
   {  
      'long':'YOU ARE CRAWLING OVER COBBLES IN A LOW PASSAGE. THERE IS A DIM LIGHT AT THE EAST END OF THE PASSAGE.',
      'short':'YOU\'RE IN COBBLE CRAWL'
   },
   {  
      'long':'YOU ARE IN A DEBRIS ROOM, FILLED WITH STUFF WASHED IN FROM THE SURFACE. A LOW WIDE PASSAGE WITH COBBLES BECOMES PLUGGED WITH MUD AND DEBRIS HERE,BUT AN AWKWARD CANYON LEADS UPWARD AND WEST. A NOTE ON THE WALL SAYS \'MAGIC WORD XYZZY\'.',
      'short':'YOU\'RE IN DEBRIS ROOM.'
   },
   {  
      'long':'YOU ARE IN AN AWKWARD SLOPING EAST/WEST CANYON.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A SPLENDID CHAMBER THIRTY FEET HIGH. THE WALLS ARE FROZEN RIVERS OF ORANGE STONE. AN AWKWARD CANYON AND A GOOD PASSAGE EXIT FROM EAST AND WEST SIDES OF THE CHAMBER.',
      'short':'YOU\'RE IN BIRD CHAMBER.'
   },
   {  
      'long':'AT YOUR FEET IS A SMALL PIT BREATHING TRACES OF WHITE MIST. AN EAST PASSAGE ENDS HERE EXCEPT FOR A SMALL CRACK LEADING ON.',
      'short':'YOU\'RE AT TOP OF SMALL PIT.'
   },
   {  
      'long':'YOU ARE AT ONE END OF A VAST HALL STRETCHING FORWARD OUT OF SIGHT TO THE WEST. THERE ARE OPENINGS TO EITHER SIDE. NEARBY, A WIDE STONE STAIRCASE LEADS DOWNWARD. THE HALL IS FILLED WITH WISPS OF WHITE MIST SWAYING TO AND FRO ALMOST AS IF ALIVE. A COLD WIND BLOWS UP THE STAIRCASE. THERE IS A PASSAGE AT THE TOP OF A DOME BEHIND YOU.',
      'short':'YOU\'RE IN HALL OF MISTS.'
   },
   {  
      'long':'THE CRACK IS FAR TOO SMALL FOR YOU TO FOLLOW.',
      'short':''
   },
   {  
      'long':'YOU ARE ON THE EAST BANK OF A FISSURE SLICING CLEAR ACROSS THE HALL. THE MIST IS QUITE THICK HERE, AND THE FISSURE IS TOO WIDE TO JUMP.',
      'short':'YOU\'RE ON EAST BANK OF FISSURE.'
   },
   {  
      'long':'THIS IS A LOW ROOM WITH A CRUDE NOTE ON THE WALL. IT SAYS \'YOU WON\'T GET IT UP THE STEPS\'.',
      'short':'YOU\'RE IN NUGGET OF GOLD ROOM.'
   },
   {  
      'long':'YOU ARE IN THE HALL OF THE MOUNTAIN KING, WITH PASSAGES OFF IN ALL DIRECTIONS.',
      'short':'YOU\'RE IN HALL OF MOUNTAIN KING.'
   },
   {  
      'long':'YOU ARE AT THE BOTTOM OF THE PIT WITH A BROKEN NECK.',
      'short':''
   },
   {  
      'long':'YOU DIDN\'T MAKE IT',
      'short':''
   },
   {  
      'long':'THE DOME IS UNCLIMBABLE',
      'short':''
   },
   {  
      'long':'YOU CAN\'T GO IN THROUGH A LOCKED STEEL GRATE!',
      'short':''
   },
   {  
      'long':'YOU DON\'T FIT DOWN A TWO INCH HOLE!',
      'short':''
   },
   {  
      'long':'YOU CAN\'T GO THROUGH A LOCKED STEEL GRATE.',
      'short':''
   },
   {  
      'long':'GAME OVER. THANK YOU FOR PLAYING!',
      'short':''
   },
   {  
      'long':'YOU ARE ON THE WEST SIDE OF THE FISSURE IN THE HALL OF MISTS.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A LOW N/S PASSAGE AT A HOLE IN THE FLOOR. THE HOLE GOES DOWN TO AN E/W PASSAGE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN THE SOUTH SIDE CHAMBER.',
      'short':''
   },
   {  
      'long':'YOU ARE IN THE WEST SIDE CHAMBER OF HALL OF MT KING. A PASSAGE CONTINUES WEST AND UP HERE.',
      'short':''
   },
   {  
      'long':'THERE IS NO WAY ACROSS THE FISSURE.',
      'short':''
   },
   {  
      'long':'YOU CAN\'T GET BY THE SNAKE',
      'short':''
   },
   {  
      'long':'YOU ARE IN A LARGE ROOM, WITH A PASSAGE TO THE SOUTH, A PASSAGE TO THE WEST, AND A WALL OF BROKEN ROCK TO THE EAST. THERE IS A LARGE \'Y2\' ON A ROCK IN ROOMS CENTER.',
      'short':'YOU\'RE AT Y2'
   },
   {  
      'long':'YOU ARE IN A JUMBLE OF ROCK, WITH CRACKS EVERYWHERE.',
      'short':''
   },
   {  
      'long':'YOU ARE AT A WINDOW ON A HUGE PIT, WHICH GOES UP AND DOWN OUT OF SIGHT. A FLOOR IS INDISTINCTLY VISIBLE OVER 50 FEET BELOW. DIRECTLY OPPOSITE YOU AND 25 FEET AWAY THERE IS A SIMILAR WINDOW.',
      'short':'YOU\'RE AT WINDOW ON PIT'
   },
   {  
      'long':'YOU ARE IN A DIRTY BROKEN PASSAGE. TO THE EAST IS A CRAWL. TO THE WEST IS A LARGE PASSAGE. ABOVE YOU IS A HOLE TO ANOTHER PASSAGE.',
      'short':'YOU\'RE IN DIRTY PASSAGE'
   },
   {  
      'long':'YOU ARE ON THE BRINK OF A SMALL CLEAN CLIMBABLE PIT. A CRAWL LEADS WEST.',
      'short':''
   },
   {  
      'long':'YOU ARE IN THE BOTTOM OF A SMALL PIT WITH A LITTLE STREAM, WHICH ENTERS AND EXITS THROUGH TINY SLITS.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A LARGE ROOM FULL OF DUSTY ROCKS. THERE IS A BIG HOLE IN THE FLOOR. THERE ARE CRACKS EVERYWHERE, AND A PASSAGE LEADING EAST.',
      'short':'YOU\'RE IN DUSTY ROCK ROOM.'
   },
   {  
      'long':'YOU HAVE CRAWLED THROUGH A VERY LOW WIDE PASSAGE PARALLEL TO AND NORTH OF THE HALL OF MISTS.',
      'short':''
   },
   {  
      'long':'YOU ARE AT THE WEST END OF HALL OF MISTS. A LOW WIDE CRAWL CONTINUES WEST AND ANOTHER GOES NORTH. TO THE SOUTH IS A LITTLE PASSAGE 6 FEET OFF THE FLOOR.',
      'short':'YOU\'RE AT WEST END OF HALL OF MISTS.'
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'YOU ARE ON THE BRINK OF A THIRTY FOOT PIT WITH A MASSIVE ORANGE COLUMN DOWN ONE WALL. YOU COULD CLIMB DOWN HERE BUT YOU COULD NOT GET BACK UP. THE MAZE CONTINUES AT THIS LEVEL.',
      'short':'YOU\'RE AT BRINK OF PIT.'
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'YOU HAVE CRAWLED THROUGH A VERY LOW WIDE PASSAGE PARALLEL TO AND NORTH OF THE HALL OF MISTS.',
      'short':''
   },
   {  
      'long':'YOU ARE AT THE EAST END OF A VERY LONG HALL APPARENTLY WITHOUT SIDE CHAMBERS. TO THE EAST A LOW WIDE CRAWL SLANTS UP. TO THE NORTH A ROUND TWO FOOT HOLE SLANTS DOWN.',
      'short':'YOU\'RE AT EAST END OF LONG HALL.'
   },
   {  
      'long':'YOU ARE AT THE WEST END OF A VERY LONG FEATURELESS HALL.',
      'short':''
   },
   {  
      'long':'YOU ARE AT A CROSSOVER OF A HIGH N/S PASSAGE AND A LOW E/W ONE.',
      'short':''
   },
   {  
      'long':'DEAD END',
      'short':''
   },
   {  
      'long':'YOU ARE AT A COMPLEX JUNCTION. A LOW HANDS AND KNEES PASSAGE FROM THE NORTH JOINS A HIGHER CRAWL FROM THE EAST TO MAKE  A WALKING PASSAGE GOING WEST THERE IS ALSO A LARGE ROOM ABOVE. THE AIR IS DAMP HERE. A SIGN IN MIDAIR HERE SAYS \'CAVE UNDER CONSTRUCTION BEYOND THIS POINT. PROCEED AT OWN RISK.\'',
      'short':''
   },
   {  
      'long':'YOU ARE IN BEDQUILT, A LONG EAST/WEST PASSAGE WITH HOLES EVERYWHERE. TO EXPLORE AT RANDOM SELECT NORTH, SOUTH, UP, OR DOWN.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A ROOM WHOSE WALLS RESEMBLE SWISS CHEESE. OBVIOUS PASSAGES GO WEST,EAST,NE, AND NW. PART OF THE ROOM IS OCCUPIED BY A LARGE BEDROCK BLOCK.',
      'short':'YOU\'RE IN SWISS CHEESE ROOM'
   },
   {  
      'long':'YOU ARE IN THE TWOPIT ROOM. THE FLOOR HERE IS LITTERED WITH THIN ROCK SLABS, WHICH MAKE IT EASY TO DESCEND THE PITS. THERE IS A PATH HERE BYPASSING THE PITS TO CONNECT PASSAGES FROM EAST AND WEST.THERE ARE HOLES ALL OVER, BUT THE ONLY BIG ONE IS ON THE WALL DIRECTLY OVER THE EAST PIT WHERE YOU CAN\'T GET TO IT.',
      'short':'YOU\'RE IN TWOPIT ROOM'
   },
   {  
      'long':'YOU ARE IN A LARGE LOW CIRCULAR CHAMBER WHOSE FLOOR IS AN IMMENSE SLAB FALLEN FROM THE CEILING(SLAB ROOM). EAST AND WEST THERE ONCE WERE LARGE PASSAGES, BUT THEY ARE NOW FILLED WITH BOULDERS. LOW SMALL PASSAGES GO NORTH AND SOUTH, AND THE SOUTH ONE QUICKLY BENDS WEST AROUND THE BOULDERS.',
      'short':'YOU\'RE IN SLAB ROOM'
   },
   {  
      'long':'YOU ARE IN A SECRET NS CANYON ABOVE A LARGE ROOM.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A SECRET N/S CANYON ABOVE A SIZABLE PASSAGE.',
      'short':''
   },
   {  
      'long':'YOU ARE IN SECRET CANYON AT A JUNCTION OF THREE CANYONS, BEARING NORTH, SOUTH, AND SE. THE NORTH ONE IS AS TALL AS THE OTHER TWO COMBINED.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A LARGE LOW ROOM. CRAWLS LEAD N, SE, AND SW.',
      'short':''
   },
   {  
      'long':'DEAD END CRAWL.',
      'short':''
   },
   {  
      'long':'YOU ARE IN SECRET CANYON WHICH HERE RUNS E/W. IT CROSSES OVER A VERY TIGHT CANYON 15 FEET BELOW. IF YOU GO DOWN YOU MAY NOT BE ABLE TO GET BACK UP',
      'short':''
   },
   {  
      'long':'YOU ARE AT A WIDE PLACE IN A VERY TIGHT N/S CANYON.',
      'short':''
   },
   {  
      'long':'THE CANYON HERE BECOMES TO TIGHT TO GO FURTHER SOUTH.',
      'short':''
   },
   {  
      'long':'YOU ARE IN A TALL E/W CANYON. A LOW TIGHT CRAWL GOES 3 FEET NORTH AND SEEMS TO OPEN UP.',
      'short':''
   },
   {  
      'long':'THE CANYON RUNS INTO A MASS OF BOULDERS - DEAD END.',
      'short':''
   },
   {  
      'long':'THE STREAM FLOWS OUT THROUGH A PAIR OF 1 FOOT DIAMETER SEWER PIPES. IT WOULD BE ADVISABLE TO USE THE DOOR.'
   }
];